from .base import FactorizedTensor
from .canonical_decomposition import CPFactorizedTensor
from .tucker_decomposition import Tucker2FactorizedTensor, Tucker3FactorizedTensor
from .lora import LoRAFactorizedTensor